### ISSUE TITLE
PWA is not working in offline mode

### ISSUE THREAD

**Issue by jnrndn** [angular-medellin/ngcolombia-2018#24]
Redirect rule is not working.

**Steps to reproduce** 

1. open [NgColomba's page](https://www.ngcolombia.com/)
2. open Chrome dev tools > network and check offline
3. reload the page
4. the page doesn't load

**Comment by jnrndn** [comment]
Seems to be a bug in `@angular/service-worker`. Refer to [this issue](https://github.com/angular/angular/issues/22362) and [this pr](https://github.com/angular/angular/pull/22883)

**Comment by jnrndn** [comment]
**Update**
downgrade the `@angular/service-worker` version to 5.1.0 also works. You can test in [this page](http://pwangcol.azurewebsites.net) 

What do you think about this @jdjuan?

**Comment by jdjuan** [comment]
So, I guess it's safe to downgrade, although I wasn't able to reproduce the fix in the URL you provided. This is what I am doing:

1. Erase cache
2. Load the website
3. Go offline in the network tab
4. Reload
5. I get the dinosaur 🤔 

Did I miss something? @jnrndn

**Comment by jnrndn** [comment]
Ha, this is funny @jdjuan 😅, clicking in that URL redirects you to my page but without `https` protocol in the URL, that's why it breaks. SW need to be served over `https`, otherwise it never gets installed and then it shows the dinosaur.

Please try again adding `https` to the URL and let me know if it works. I tried it in my phone in a place with awful mobile network conncetion and it worked great.

**Comment by jdjuan** [comment]
Alright, so I tried in my phone and it worked great! 👍 
Yet when I tried in my browser I couldn't make it work. @leono286 @luchillo17 can you verify, I guess @jnrndn is on vacations and doesn't have a laptop around 😝

**Comment by luchillo17** [comment]
Ja, got it working and can reproduce the bug as well, try this url with service worker:
https://www.ngcolombia.com/index.html

**Comment by luchillo17** [comment]
Had to clear the app storage & service workers but now it's working for me.

**Comment by Aarchana** [comment]
Hi I created a simple angular application with service worker flag using angular-cli and I am serving that through the firebase which internally uses https when i see in the console i see service worker as running and when i go offline and try to refresh the page the cache-bust call that it makes to server fails and it throws me 504 gateway error. Can anyone help on this.

**Comment by jdjuan** [comment]
Nevermind, it must be me. Probably I still have some old service worker 🤔. Go on @jnrndn

**Comment by jdjuan** [comment]
@Aarchana you arrived at the right place. @jnrndn is our Service Worker expert. Although I believe that creating a repo reproducing the error might make it easier for us to help you out 😃

**Comment by kavinRkz** [comment]
I have also problem on encryption and decryption on indexed data..encryption and decryption perfectly working on online mode..in offline mode data cannot decrypted...plz give me a solution its urgent

**Comment by Nazirkulov** [comment]
HI [jnrndn](/jnrndn) i go to your web site [NgColomba's page](https://www.ngcolombia.com/) and it still not working in offline mode. Are you fix it or not ? 
I have the same problem with demo app from angular.io website. It nice work localy in offline mode from http://localhost:8080 and http://127.0.0.1:8080 but not working with httpS and local ip adress like 10.70....:8080 or 192.168....:8080
