### ISSUE TITLE
Speakers

### ISSUE THREAD

**Issue by jdjuan** [angular-medellin/ngcolombia-2018#28]
# Speakers Mobile

![speakers_mobile](https://user-images.githubusercontent.com/3171900/39676552-4559e478-5132-11e8-96d1-a893f292e169.jpg)

# Popup Mobile

![pop up](https://user-images.githubusercontent.com/3171900/39676549-45113098-5132-11e8-9ffc-64f33f191d21.png)

# Speakers Desktop

![speakers](https://user-images.githubusercontent.com/3171900/39676551-4541eba2-5132-11e8-8dc3-e5e6b913f8a1.jpg)

# Popup Desktop

![popup](https://user-images.githubusercontent.com/3171900/39676550-452a5e2e-5132-11e8-9fdd-1b617807c2e6.jpg)

**Comment by luchillo17** [comment]
Nice, on it.

**Comment by luchillo17** [comment]
UI mostly done, lacks adjustments in layout for responsiveness.

**Comment by jdjuan** [comment]
ok
