### ISSUE TITLE
Implement Ticket section

### ISSUE THREAD

**Issue by jdjuan** [angular-medellin/ngcolombia-2018#57]
Use the same format as Speakers but in the second page put this:

![tickets](https://user-images.githubusercontent.com/3171900/41776501-9f44290a-75ed-11e8-9a9b-d469779637eb.png)

**Comment by royalcas** [comment]
This is the current version
![image](https://user-images.githubusercontent.com/7102342/41810254-302fc0cc-76c1-11e8-9079-ae691b67a37d.png)
